import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
TELEGRAM_CHANNEL_ID = os.getenv('TELEGRAM_CHANNEL_ID')
TELEGRAM_CHANNEL_NAME = os.getenv('TELEGRAM_CHANNEL_NAME', 'Our Channel')
ADMIN_TELEGRAM_UID = int(os.getenv('ADMIN_TELEGRAM_UID', 0))

MIN_DEPOSIT = 1
MAX_DEPOSIT = 10000
MIN_WITHDRAWAL = 150

MAX_DOCUMENT_SIZE = 300 * 1024
MAX_VIDEO_SIZE = 10 * 1024 * 1024

REFERRAL_BONUS = 50

PAYMENT_VERIFICATION_DELAY = 120
